name: auto-test

on: 
  push: 
    branches: [trade-demo]

jobs:
  run-automation-test:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build
      run: |
        mvn --batch-mode -DskipTests package
    - name: Test
      run: |
        mvn -Dtest=Authorization_Login test
#     - name: Report
#       uses: dorny/test-reporter@v1
#       if: always()
#       with:
#         name: Maven Tests
#         path: target/surefire-reports/*.xml
#         reporter: java-junit
#         fail-on-error: true
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: ${{ github.workspace }}/target/surefire-reports/junitreports/*.xml
        reporter: java-junit
        java-version: 14
        fail-on-error: true
    - name: Upload test result as an artifact
      if: always()
      uses: actions/upload-artifact@v1
      with: 
        name: test_result
        path: target/surefire-reports
        
